import korlibs.korge.gradle.*
import korlibs.korge.gradle.Orientation
import java.io.File


plugins {
    alias(libs.plugins.korge)
    id("com.google.gms.google-services") version "4.4.4"
}


korge {
    id = "com.kimhietee.endless"
    name = "Endless"
    androidMinSdk = 23
    androidTargetSdk = 34
    androidCompileSdk = 34
    targetJvm()
    targetJs()
    targetWasmJs()
    targetAndroid()
    serializationJson()
    orientation = Orientation.LANDSCAPE
}


dependencies {
    add("commonMainApi", project(":deps"))
    add("commonMainImplementation", "dev.gitlive:firebase-auth:1.13.0")
    add("commonMainImplementation", "dev.gitlive:firebase-firestore:1.13.0")
    add("commonMainImplementation", "dev.gitlive:firebase-analytics:1.13.0")
}


// Copy google-services.json to correct locations
tasks.register("copyGoogleServices") {
    description = "Copy google-services.json to project root and deps subproject for Android builds"
    doLast {
        val sourceFile = File(project.projectDir, "src/androidMain/google-services.json")
        if (!sourceFile.exists()) {
            println("[Build] ⚠️  WARNING: google-services.json not found at ${sourceFile.absolutePath}")
            return@doLast
        }
        val rootDest = File(project.projectDir, "google-services.json")
        sourceFile.copyTo(rootDest, overwrite = true)
        println("[Build] ✓ Copied google-services.json to project root: ${rootDest.absolutePath}")
        val depsDest = File(project.projectDir, "deps/google-services.json")
        sourceFile.copyTo(depsDest, overwrite = true)
        println("[Build] ✓ Copied google-services.json to deps: ${depsDest.absolutePath}")
    }
}


tasks.matching { it.name.contains("Android") || it.name.contains("android") }.configureEach {
    dependsOn("copyGoogleServices")
}


val sourceGoogleServices = File(project.projectDir, "src/androidMain/google-services.json")
if (sourceGoogleServices.exists()) {
    val rootDest = File(project.projectDir, "google-services.json")
    if (!rootDest.exists() || sourceGoogleServices.readText() != rootDest.readText()) {
        sourceGoogleServices.copyTo(rootDest, overwrite = true)
    }
    val depsDest = File(project.projectDir, "deps/google-services.json")
    if (!depsDest.exists() || sourceGoogleServices.readText() != depsDest.readText()) {
        sourceGoogleServices.copyTo(depsDest, overwrite = true)
    }
}


// Apply google-services plugin to Android subproject generated by KorGE
subprojects {
    afterEvaluate {
        if (plugins.hasPlugin("com.android.application")) {
            apply(plugin = "com.google.gms.google-services")
            val googleServicesFile = File(rootProject.projectDir, "google-services.json")
            val destFile = File(project.projectDir, "google-services.json")
            if (googleServicesFile.exists()) {
                googleServicesFile.copyTo(destFile, overwrite = true)
                println("[Build] ✓ Copied google-services.json to Android subproject: ${destFile.absolutePath}")
            }
        }
    }
}



